trigger:
- main

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Build the Docker image
    docker build -t my-docker-image:latest -f gowshi77gowshi/Docka_Maven/Dockerfile .

    # Check if the image was built successfully
    if [ $? -eq 0 ]; then
      echo "Docker image built successfully."
    else
      echo "Failed to build Docker image."
      exit 1
    fi
  displayName: 'Build Docker Image'

- script: |
    # Install Trivy (if not already installed)
    if [ ! -x "$(command -v trivy)" ]; then
      curl -sfL https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m) -o ~/trivy
      chmod +x ~/trivy
      export PATH=$PATH:~/ # Add Trivy to the PATH
    fi

    # Scan the Docker image using Trivy
    trivy image my-docker-image:latest
  displayName: 'Scan Docker Image with Trivy'
